- name: Set logstash to run as root
  action: >
     lineinfile dest=/etc/sysconfig/logstash state=present
     regexp="^LS_USER="
     line='LS_USER=root'
  notify: Restart Logstash

- name: Install Logstash Local yum configuration
  template: src=10-yum.conf dest=/etc/logstash/conf.d/10-yum.conf
