---
- name: Install the central node
  hosts: aggregator
  sudo: yes
  roles:
    - esnode
    - aggregator
    - kibana
      
- name: Install extra Elasticsearch nodes
  hosts: esnodes
  sudo: yes
  roles:
    - esnode
    
- name: Install Logstash on DNS Servers
  hosts: dns-servers
  sudo: yes
  roles:
    - logstash

- name: Install the Packetbeat and Logstash agents on Cpanel Servers
  hosts: cpanel-servers
  sudo: yes
  roles:
    - packetbeat
    - logstash
