---
- name: Install the Packetbeat central node
  hosts: aggregator
  sudo: yes
  roles:
    - esnode
    - aggregator
    - kibana
    
- name: Install Logstash agents and extra Elasticsearch nodes
  hosts: dns-servers
  sudo: yes
  roles:
    - logstash
    - esnode

- name: Install the Packetbeat and Logstash agents
  hosts: cpanel-servers
  sudo: yes
  roles:
    - packetbeat
    - logstash
