- include: debian.yml
  when: ansible_os_family == 'Debian'

- include: redhat.yml
  when: ansible_os_family == 'RedHat'

- name: Configure Packetbeat
  template: src=packetbeat.conf dest=/etc/packetbeat/packetbeat.conf
  notify: Restart Packetbeat

- name: Start Packetbeat
  service: name=packetbeat state=started
