- name: Install REDIS
  apt: pkg=redis-server state=present update_cache=yes
  tags: deps

- name: Install dependencies
  apt: pkg={{ item }} update_cache=yes state=present
  with_items:
   - python-pycurl
   - python-apt
   - python-setuptools
   - libapache2-mod-php5
   - php5-cli
   - php5-mysql
   - php5-gd
   - php5-snmp
   - php-pear
   - snmp
   - graphviz
   - php5-mcrypt
   - php5-json
   - subversion
   - mysql-server
   - mysql-client
   - rrdtool
   - fping
   - imagemagick
   - whois
   - mtr-tiny
   - nmap
   - ipmitool
   - python-mysqldb
   - curl
   - libcurl3
  tags: deps

- easy_install: name=pip
  tags: deps

- name: Install ES Curator
  pip: name=elasticsearch-curator
  tags: deps

- name: Configure Redis
  template: src=redis.conf dest=/etc/redis/redis.conf
  notify: Restart Redis

- name: Add Logstash repository
  apt_repository: repo="deb http://packages.elasticsearch.org/logstash/{{ aggregator.logstash_version }}/debian stable main" state=present

- name: Add Logstash repository key
  apt_key: url="http://packages.elasticsearch.org/GPG-KEY-elasticsearch" state=present

- name: Install Logstash
  apt: pkg={{ item }} update_cache=yes state=present
  with_items:
   - logstash
   - logstash-contrib

- name: Logstash set heap size
  action: >
     lineinfile dest=/etc/init.d/logstash state=present
     regexp="^LS_HEAP_SIZE="
     line='LS_HEAP_SIZE="{{aggregator.config.logstash_heap_size|int}}m"'
  notify: Restart Logstash

- name: register templates
  local_action: shell ls {{ inventory_dir }}/roles/aggregator/templates/logstash
  register: template_files
  
- template: src={{ item }} dest=/etc/logstash/conf.d/{{item}}
  with_items: template_files.stdout_lines
  notify: Restart Logstash

- name: Schedule curator for ES
  cron: >
        name='Curate Logs'
        hour=3 minute=15
        job="{{ curator_bin }} --host {{ aggregator_bind_ip }} delete --older-than {{ aggregator.config.days_of_history }}"
        user=root cron_file=ES_curator
